# Generated by Django 3.1.4 on 2020-12-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_room', models.CharField(max_length=50, verbose_name='name_room')),
                ('is_active', models.BooleanField(default=False, verbose_name='esta activo')),
            ],
        ),
        migrations.CreateModel(
            name='StreamTokenUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100, verbose_name='channel name')),
                ('rol_user', models.PositiveIntegerField(verbose_name='rol user')),
            ],
        ),
    ]
